# Network
scanner.subnet=192.168.1
scanner.timeout=200

# Common ports (QuickScanStrategy)
scanner.common-ports=22,80,443,8000,8080,8443

# Thread pool
scanner.pool-size=50

# Tempo máximo de espera para conclusão das varreduras maiores (segundos)
scanner.stable-wait=90
scanner.full-wait=180

# Banner grabbing
banner.enabled=true
banner.timeout=1500
banner.max-bytes=512
banner.probe-ports=80,8080,8000,443,8443

# Database
database.url=jdbc:sqlite:network-monitor.db
