# Network
scanner.subnet=192.168.0
scanner.timeout=200

# Common ports (QuickScanStrategy)
scanner.common-ports=22,80,443,8000,8080,8443

# Thread pool
scanner.pool-size=50

# Database
database.url=jdbc:sqlite:network-monitor.db
